import './globals.css';
import type { Metadata } from 'next';
import Header from '@/components/common/Header';
import AuthProvider from '@/Providers/AuthProvier';
import QueryProvider from '@/Providers/QueryProvider';
import Sidebar from '@/components/common/Sidebar';
import { db } from '@/lib/prisma';
import { getServerSession } from 'next-auth';
import { authOptions } from './api/auth/[...nextauth]/route';
import type { Summary } from '@prisma/client';
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);

  let summaries: Summary[] = [];

  if (session?.user?.id) {
    summaries = await db.summary.findMany({
      where: { userId: session.user.id },
    });
  }

  return (
    <html lang='en' className='h-full'>
      <body className='h-full'>
        <AuthProvider>
          <div className='flex h-full '>
            <Sidebar summaries={summaries} />

            <div className='flex flex-col flex-1'>
              <Header />
              <QueryProvider>{children}</QueryProvider>
            </div>
          </div>
        </AuthProvider>
      </body>
    </html>
  );
}
