import './globals.css';
import type { Metadata } from 'next';
import Header from '@/components/common/Header/Header';
import Sidebar from '@/components/common/Sidebar/Sidebar';
import AuthProvider from '@/Providers/AuthProvier';
import QueryProvider from '@/Providers/QueryProvider';
// import { getSummaries } from '@/lib/summary';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const summaries = await getSummaries();

  return (
    <html lang='en' className='h-full'>
      <body className='h-full'>
        <QueryProvider>
          <AuthProvider>
            <div className='flex h-full '>
              {/* <Sidebar summaries={summaries} /> */}
              <Sidebar />
              <div className='flex flex-col flex-1'>
                <Header />
                {children}
              </div>
            </div>
          </AuthProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
