import './globals.css';
import type { Metadata } from 'next';
import Header from '@/components/common/Header';
import AuthProvider from '@/Providers/AuthProvier';
import QueryProvider from '@/Providers/QueryProvider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body>
        <AuthProvider>
          <Header />
          <QueryProvider>{children}</QueryProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
